appConfig:
  Env: "local"

webConfig:
  ListenAddress: ":8888"
  ReadTimeout: 15
  WriteTimeout: 15

postgresConfig:
  DbHost: "postgres"
  DbPort: 5432
  DbUser: "postgres"
  DbPassword: "veryStrongPassword"
  DbName: "prReviewsDB"
  DbSslMode: "disable"

metricsConfig:
  ListenAddr: ":9100"
  Name: "pr_control_service"
